### PR TITLE
docs: Switch to mdbook, rework

### PR DESCRIPTION
**Pull request by cgwalters**
- I don't want my life to involve ruby, and in particular `mdbook serve` Just Works out of the box with a single binary
- Reorganize the sections
- Some content cleanup and fixes
- Integrate the man pages into the docs (hooray!)

### CODE REVIEW

**Comment by cgwalters** [comment]
[Rendered](https://cgwalters.github.io/bootc/)

**Review by jmarrero — APPROVED** [review]
lgtm

**Review by vrothberg — APPROVED** [review]
LGTM
Restarted the failed job.

**Comment by cgwalters** [comment]
"CI / Container testing (pull_request)" is going to be broken until https://github.com/authselect/authselect/pull/368 is merged, and I will go nag there

**Pull request merged**
