### PR TITLE
test: update ami image id

### PR DESCRIPTION
**Pull request by henrywang**
This PR is to update ami id to latest according to compose update.

### CODE REVIEW

**Comment by henrywang** [comment]
Hi @cgwalters! Test is runing into an error `Failed to invoke skopeo proxy method FinishPipe`. This error should be the same as issue https://github.com/coreos/rpm-ostree/issues/4567.
I retired twice and can't make it green.

**Comment by cgwalters** [comment]
It's always been a race condition AFAICS, but unfortunate we're seeing it here too.

**Comment by cgwalters** [comment]
As far as these AMI updates, I think we should probably configure renovate to do it.

**Comment by henrywang** [comment]
> As far as these AMI updates, I think we should probably configure renovate to do it.

This ami id will be used by at least two repos(`bootc` and `bootc-workflow-test`), I'll save ami id into `AWS Systems Manager (SSM) Parameter Store`. There's a CI in https://github.com/virt-s1/bootc-workflow-test/blob/main/.github/workflows/upload_rhel9_ami.yml. The CI includes a fully test for new ami. So I'll update this CI to deploy test passed ami id to `AWS Systems Manager (SSM) Parameter Store` instead of update the ami id in playbook.

**Review by cgwalters — APPROVED** [review]

**Pull request merged**
