### PR TITLE
mdbook linkcheck

### PR DESCRIPTION
**Pull request by jeckersb**
- **ci/docs: Add mdbook-linkcheck**
- **docs: fix mdbook-linkcheck errors/warnings**

### CODE REVIEW

**Comment by miabbott** [comment]
@jeckersb I was tinkering on this as well...I think I have something nearly working here - https://github.com/miabbott/bootc/commit/aa14b97f7ad457dcc21d836eb601dd826c626355

Feel free to borrow anything from that

**Comment by henrywang** [comment]
Please ignore rhel 9.4 integration test failure. The new `rhel9-rhel_bootc:rhel-9.4` image sets `Compose ID` to ''. So the `/etc/yum.repo.d/rhel-9.repo` can't be configured without `Compose ID`. I'll update the test in another PR later to fix this issue.

**Comment by jeckersb** [comment]
Alright I think this is doing the right thing and is ready for review now.  I initially tried to make the mdbook setup bits into a reusable workflow, but that didn't quite work and I think what we would really want to share that code is a reusable action.  But the github docs seem to imply that the action would need to live by itself in its own repository, which seems like more trouble than it's worth.  So at least for now I've elected to go the copy/paste code duplication route.

**Review by cgwalters — APPROVED** [review]
Nice, thanks!

**Comment by miabbott** [comment]
@jeckersb how about modifying `docs.yml` to run on PRs?

<details>

```diff
diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
index 1a04ff0..57968a8 100644
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -144,7 +144,7 @@ jobs:
       - name: Integration tests
         run: |
           set -xeuo pipefail
-          image=quay.io/centos-bootc/centos-bootc-dev:stream9 
+          image=quay.io/centos-bootc/centos-bootc-dev:stream9
           echo 'ssh-ed25519 ABC0123 testcase@example.com' > test_authorized_keys
           sudo podman run --rm --privileged -v ./test_authorized_keys:/test_authorized_keys --env RUST_LOG=debug -v /:/target -v /var/lib/containers:/var/lib/containers -v ./usr/bin/bootc:/usr/bin/bootc --pid=host --security-opt label=disable \
             ${image} bootc install to-filesystem --acknowledge-destructive \
@@ -199,34 +199,3 @@ jobs:
           truncate -s 20G ${tmpdisk}
           sudo podman run --rm --privileged --env RUST_LOG=debug -v /dev:/dev -v /:/target -v /var/lib/containers:/var/lib/containers -v ./usr/bin/bootc:/usr/bin/bootc --pid=host --security-opt label=disable \
             -v ${tmpdisk}:/disk ${image} bootc install to-disk --via-loopback /disk
-  docs:
-    if: ${{ contains(github.event.pull_request.labels.*.name, 'documentation') }}
-    runs-on: ubuntu-latest
-    env:
-      MDBOOK_VERSION: 0.4.37
-    steps:
-      - uses: actions/checkout@v4
-      - name: Install mdBook
-        run: |
-          tag=$(curl 'https://api.github.com/repos/rust-lang/mdbook/releases/latest' | jq -r '.tag_name')
-          url="https://github.com/rust-lang/mdbook/releases/download/${tag}/mdbook-${tag}-x86_64-unknown-linux-gnu.tar.gz"
-          mkdir mdbook
-          curl -sSL $url | tar -xz --directory=./mdbook
-          echo `pwd`/mdbook >> $GITHUB_PATH
-      - name: Install mdbook-mermaid
-        run: |
-          tag=$(curl 'https://api.github.com/repos/badboy/mdbook-mermaid/releases/latest' | jq -r '.tag_name')
-          url="https://github.com/badboy/mdbook-mermaid/releases/download/${tag}/mdbook-mermaid-${tag}-x86_64-unknown-linux-gnu.tar.gz"
-          mkdir mdbook-mermaid
-          curl -sSL $url | tar -xz --directory=./mdbook-mermaid
-          echo `pwd`/mdbook-mermaid >> $GITHUB_PATH
-      - name: Install mdbook-linkcheck
-        run: |
-          tag=$(curl 'https://api.github.com/repos/Michael-F-Bryan/mdbook-linkcheck/releases/latest' | jq -r '.tag_name')
-          archive="mdbook-linkcheck.x86_64-unknown-linux-gnu.zip"
-          url="https://github.com/Michael-F-Bryan/mdbook-linkcheck/releases/download/${tag}/${archive}"
-          mkdir mdbook-linkcheck
-          curl -sSL -O $url && unzip ${archive} -d ./mdbook-linkcheck && chmod +x ./mdbook-linkcheck/mdbook-linkcheck
-          echo `pwd`/mdbook-linkcheck >> $GITHUB_PATH
-      - name: Build with mdBook
-        run: cd docs && mdbook-mermaid install && mdbook build
diff --git a/.github/workflows/docs.yml b/.github/workflows/docs.yml
index a7f210f..a0caa44 100644
--- a/.github/workflows/docs.yml
+++ b/.github/workflows/docs.yml
@@ -3,6 +3,8 @@ name: Deploy docs to pages
 on:
   push:
     branches: ["main"]
+  pull_request:
+      branches: [main]
   workflow_dispatch:
 
 permissions:
@@ -16,6 +18,7 @@ concurrency:
 
 jobs:
   build:
+    if: ${{ contains(github.event.pull_request.labels.*.name, 'documentation') }}
     runs-on: ubuntu-latest
     env:
       MDBOOK_VERSION: 0.4.37
```

</details>

**Pull request merged**
