### PR TITLE
Use published ostree-ext 0.10

### PR DESCRIPTION
**Pull request by cgwalters**
I just pushed this out, should fix the `cargo deny` failures.

### CODE REVIEW

**Review by travier — APPROVED** [review]

**Comment by cgwalters** [comment]
@travier I invited you to be a maintainer here so the approval works :smile:

**Review by travier — APPROVED** [review]

**Review by travier — APPROVED** [review]

**Comment by travier** [comment]
🤔

**Review by travier — APPROVED** [review]

**Review by travier — APPROVED** [review]
LGTM

**Comment by travier** [comment]
Hum, weird.

**Comment by cgwalters** [comment]
Hmm.  It may be that the status here is "sticky" from your prior state as a non-maintainer.  Can you try approving https://github.com/containers/bootc/pull/11 ?

**Pull request merged**
