### PR TITLE
test: Remove tmt bootc plugin code and use released bootc plugin

### PR DESCRIPTION
**Pull request by henrywang**
Remove tests-intetration folder because TMT bootc plugin replaces tests-integration

### CODE REVIEW

**Comment by cgwalters** [comment]
Thanks for looking at this! I had started on a similar patch but it started to get big and so I did just https://github.com/containers/bootc/pull/937

These don't logically conflict but let's land 937 first?

**Comment by cgwalters** [comment]
Hmm but now we entirely lost the tmt tests running on PRs here?

**Comment by cgwalters** [comment]
Test jobs seem dead now with
> fatal: not a git repository (or any parent up to mount point /)

**Comment by henrywang** [comment]
Yes! I got everything works now.

**Review by cgwalters — APPROVED** [review]
Nice!

**Pull request merged**
