### PR TITLE
tests: Fix lbi test

### PR DESCRIPTION
**Pull request by cgwalters**
tests: Adapt for newer nushell

It looks like the default `column1` became `column0` which
broke this. But really we don't need a table, we just need a list;
and piping to `from csv` was a weird way to go about splitting
lines into a list.

Change the assertion to just expect a list which simplifies
the code.

---

Drop copy of tmt bootc plugin

It's now merged and shipped, and us having a copy breaks things.

Signed-off-by: Colin Walters <walters@verbum.org>

---

Closes: https://github.com/containers/bootc/issues/936

### CODE REVIEW

**Comment by cgwalters** [comment]
One thing I hadn't realized is that nushell is still [making breaking changes](https://github.com/nushell/nushell/issues?q=label%3Apr%3Abreaking-change+is%3Aclosed) - this is the second one of these that bit us, and I don't think we have really complex/unusual code here.

This makes me less sanguine about using it for this but...for now let's just keep this and hope it settles down.

**Comment by cgwalters** [comment]
Huh, the integration test there hit
> ERROR Switching: Pulling: Importing: Parsing layer blob sha256:73a9da8ed490b51b03fe0109a75cea245a5fda85410ebd76820aeb110854a7f5: failed to invoke method FinishPipe: failed to invoke method FinishPipe: write |1: broken pipe

Again...I thought we'd had that one fixed!

**Comment by jeckersb** [comment]
> Huh, the integration test there hit
> 
> > ERROR Switching: Pulling: Importing: Parsing layer blob sha256:73a9da8ed490b51b03fe0109a75cea245a5fda85410ebd76820aeb110854a7f5: failed to invoke method FinishPipe: failed to invoke method FinishPipe: write |1: broken pipe
> 
> Again...I thought we'd had that one fixed!

Do not like :-1:

**Comment by cgwalters** [comment]
Rebased just to see if that helps

**Comment by cgwalters** [comment]
YES! Integration tests passed again.

**Review by henrywang — APPROVED** [review]

**Pull request merged**
