### PR TITLE
test: add centos stream 10 rpm build and e2e test

### PR DESCRIPTION
**Pull request by henrywang**
This PR includes:

1. add centos stream 10 all arch rpm build
2. add e2e test for centos stream 10

### CODE REVIEW

**Comment by henrywang** [comment]
Hi @lukewarmtemp, I found `systemd.unified_cgroup_hierarchy=0` was added in PR https://github.com/containers/bootc/pull/594.

I have to remove it in this PR because it caused boot failure on CS10 with error: `[!!!!!!] Refusing to run under cgroup v1, SY… specified on kernel command line.` CS10 deprecated boot from cgruop v1.

Does removing this karg impact test? Thanks.

**Comment by lukewarmtemp** [comment]
> I there any test impact of remove this karg? Thanks.

You're free to remove it. Sorry, I just arbitrarily chose some kargs to test and didn't realize that it might conflict with others.

**Comment by cgwalters** [comment]
Yes, we should definitely not set that.

**Comment by henrywang** [comment]
> Looks sane, though one issue is the matrix here is getting pretty large, and fairly often we hit "artemis" provisioning failures e.g.

Yes. The most of time (99%) the provisioning issue happens on x86_64 runner machine. Looks the aarch64 runner does not hit the quota.

- In `to-disk` test, I removed `centos-stream-9-x86_64` and added `centos-stream-10-x86_64`. No additional x86_64 test added.
- I added `centos-stream-10-aarch64` in both `to-disk` and `to-existing-root` tests.

**Pull request merged**
