### PR TITLE
install: Force mkfs.xfs to overwrite

### PR DESCRIPTION
**Pull request by sacsant**
Reusing a disk (after manually deleting partitions on it) with xfs
as file system, install to-disk command fails complaning about
existing file system on root partition.

Creating root filesystem (xfs) on device /dev/sdb2 (size=107.4 GB)
> mkfs.xfs -m uuid=4826aa5b-0dd0-4382-a0c1-7c0b77cfd47d -L root /dev/sdb2
mkfs.xfs: /dev/sdb2 appears to contain an existing filesystem (xfs). 
mkfs.xfs: Use the -f option to force overwrite.

Use the -f option with mkfs.xfs to force overwrite.

Signed-off-by: Sachin Sant <sachinp@linux.ibm.com>

### CODE REVIEW

**Comment by cgwalters** [comment]
Hm, you got this even when specifying `--wipe`? Or did you run wipefs manually?

**Comment by cgwalters** [comment]
>  (after manually deleting partitions on it) 

Ah yes you did say that. Well...we have `to-disk --wipe` for this reason which note explicitly clears each child device too. (I don't know why `wipefs` doesn't have `--recursive` or so...probably wouldn't be hard to add)

How about: Only if `--wipe` is passed then we also pass `-f` to the mkfs invocations?

**Comment by cgwalters** [comment]
There's a flip side to this in that this "existing partitions" check is the only thing right now that stops one from actively destroying e.g. the booted disk if `--wipe` is used: we definitely need to strengthen the `to-disk` path to bail hard if the device is mounted for example, even if `--wipe` is specified.

(xref https://lwn.net/Articles/941764/ )

**Review by cgwalters — APPROVED** [review]
Great, thanks!

**Comment by cgwalters** [comment]
(This was missing a `cargo fmt`; in this repo remember to run `make validate` before pushing)

**Comment by sacsant** [comment]
> (This was missing a `cargo fmt`; in this repo remember to run `make validate` before pushing)

Thanks. Will take care of this requirement for future PRs.

**Pull request merged**
