### PR TITLE
cli: Add build-commit

### LINKED ISSUE #216: Add `bootc build commit`
This should take over the role of `ostree container commit`, however following up on https://github.com/ostreedev/ostree-rs-ext/pull/569 we can change our thoughts on `/var`.

### PR DESCRIPTION
**Pull request by jmarrero**
Closes #216

### CODE REVIEW

**Comment by jmarrero** [comment]
mm I think I need to use the ostree-ext crate directly instead of just calling ostree.

**Review by sallyom — COMMENTED** [review]
@jmarrero do you want to convert to PR?

**Comment by cgwalters** [comment]
So one big thing we could do here in general is a lot of what happens today in the rpm-ostree postprocessing phase; for example, a big one is handling `/etc/passwd` and generating sysusers fragments.

Another interesting one is kernel handling; erroring out if you have multiple kernels, cleaning up the duplicate content the Fedora kernel packages drop in `/boot` etc.

However...lately I'm also thinking just for maximum compatibility we should start to do that stuff on the client too automatically.

**Comment by jmarrero** [comment]
Did not get it our of Draft because of background chats with Colin, sorry for not updating sooner. I think we wanted, to make this bootc native code instead of calling back to ostree to reduce the dep on ostree and on top of that the logic with /var changes needs to be revised.

What do you guys think about:
1) check for stuff in /tmp and error out
2) relax the /var errors make it warning 
3)  any other check?

**Comment by cgwalters** [comment]
Or maybe what would be best is something like a generalized "hooks" framework, i.e. we have `/usr/lib/bootc/container-commit.d` that contains drop-ins that can execute at build time.  That would make everything easily extensible...and today we have sysusers code in rpm-ostree that we could keep where it is, and have e.g.

```
cat /usr/lib/bootc/container-commit.d/10-rpmostree-sysusers
#!/bin/bash
exec rpm-ostree postprocess sysusers
```
or so?

**Comment by jmarrero** [comment]
I guess that would work, but we would need also to scan the dropins and skip anything calling binaries not present on the system? Or just fail with a warning? Because in your example we would fail in an image that does not have rpm-ostree.

**Pull request closed without merging**
