### PR TITLE
install: Disable fsync() in repo when pulling && improved pull progress

### PR DESCRIPTION
**Pull request by cgwalters**
See individual patches. Motivated by https://github.com/containers/bootc/discussions/646

### CODE REVIEW

**Comment by cgwalters** [comment]
@henrywang Hmm,

```
fatal: [guest]: FAILED! => changed=false 
  assertion: result_booted_cachedupdate_digest.stdout == result_rollback_image_digest.stdout
```

Have you see this in other PRs? I think it'd be helpful to acquire the full systemd journal here, is that easily doable?

**Comment by jeckersb** [comment]
Overall looks great to me.  The only thing is that it appears to cut off the `byte_bar` at 80 characters, which looks weird on a wider terminal and cuts off the majority of the message.  Ends up like:
```
 └ Fetching ██████████████████░░ 127.51 MiB/136.26 MiB (232.34 MiB/s) layer sha2
```
I'm not familiar with `indicatif` but I'll see if I can make it use more space when it's available.

**Comment by cgwalters** [comment]
Yeah, I finally figured out that mutating the `{prefix}` were what was causing the "eating previous terminal output" behavior I saw in previous changes here, and I switched to setting `{msg}` which is how things are intended to work. But indeed it seems like the library isn't detecting the terminal width correctly, or something else is going wrong. Could add a `dbg!` with https://docs.rs/indicatif/latest/indicatif/trait.TermLike.html#tymethod.width ?

**Comment by cgwalters** [comment]
Figured it out https://github.com/containers/podman-bootc/pull/55

**Comment by jeckersb** [comment]
> Figured it out [containers/podman-bootc#55](https://github.com/containers/podman-bootc/pull/55)

Nice, I had gotten as far as:

https://github.com/console-rs/console/blob/master/src/unix_term.rs#L46-L64

And determined that `isatty` is correctly returning `1` but the `ioctl` is leaving the winsize rows and cols as `0` so it falls back to the default width of `80`.

**Review by jeckersb — APPROVED** [review]
Confirmed this works like a charm with the `podman-bootc` fix :tada:

**Pull request merged**
