### PR TITLE
install: Fall back to `setenforce 0` if needed

### PR DESCRIPTION
**Pull request by cgwalters**
I've opened https://github.com/containers/bootc/issues/83 to track a better fix.

### CODE REVIEW

**Comment by cgwalters** [comment]
cc @rhatdan - Trying really hard here to not `setenforce 0` but failing.  For some reason I don't understand, the domain transition from a container image executing as `unconfined_t` running an `install_exec_t` file just doesn't transition to `install_t`.  Trying to do e.g. 
```
$ podman run --rm -ti --privileged --security-opt label=type:install_t quay.io/centos/centos:stream9 true
{"msg":"exec container process `/usr/bin/true`: Permission denied","level":"error","time":"2023-03-21T13:09:14.616124Z"}
```
fails, etc.

**Comment by rhatdan** [comment]
This is a container-selinux issue.

https://github.com/containers/container-selinux/pull/222

**Comment by rhatdan** [comment]
Fixed in https://github.com/containers/container-selinux/releases/tag/v2.206.0

**Comment by cgwalters** [comment]
Nice, thanks!

The good thing at least here is that while this PR is a hack, it is at least designed such that we only fall back to `setenforce 0` if our "re-exec as install_t" trick doesn't work.

**Pull request merged**
